In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report

In [2]:
data = pd.read_csv("C:\\Users\\Nitin\\OneDrive\\Desktop\\BTECH 2nd sem\\Diabetes_prediction_AgenticAi\\Dataset\\pima_diabetes_preprocessed.csv")
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,209.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,73.0,26.6,0.351,31,0
2,8,183.0,64.0,29.4,383.2,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [3]:
x=data.drop(["Outcome","DiabetesPedigreeFunction"],axis=1)
y=data["Outcome"]
#test train split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

model = RandomForestClassifier(n_estimators=600,random_state=42,class_weight="balanced")
model.fit(X_train_scaled,y_train)
x.head()

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  Age
0            6    148.0           72.0           35.0    209.0  33.6   50
1            1     85.0           66.0           29.0     73.0  26.6   31
2            8    183.0           64.0           29.4    383.2  23.3   32
3            1     89.0           66.0           23.0     94.0  28.1   21
4            0    137.0           40.0           35.0    168.0  43.1   33

In [4]:
y_pred = model.predict(X_test_scaled)
print("accuracy:",accuracy_score(y_test,y_pred))
print("confusion matrix: ",confusion_matrix(y_test,y_pred))
print("\nclassification_report \n",classification_report(y_test,y_pred))

accuracy: 0.7467532467532467
confusion matrix:  [[77 22]
 [17 38]]

classification_report
               precision    recall  f1-score   support

           0       0.82      0.78      0.80        99
           1       0.63      0.69      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154

In [5]:
# #save the model
# import pickle

# pickle_model_path = 'model.pkl'
# with open(pickle_model_path, 'wb') as f:
#     pickle.dump(model, f)